# Generated by Django 3.2.6 on 2021-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='hTGF0xmKR0ps8VCNMkdg3C3xcPfLru3Z', max_length=32, unique=True, verbose_name='Token')),
                ('counter', models.SmallIntegerField(default=0, verbose_name='View Count')),
                ('enabled_count', models.SmallIntegerField(default=0, verbose_name='View Limit')),
                ('enabled_to', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
