# Generated by Django 3.2.6 on 2021-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='counter',
            field=models.SmallIntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AlterField(
            model_name='token',
            name='enabled_count',
            field=models.SmallIntegerField(default=0, verbose_name='View Limit'),
        ),
        migrations.AlterField(
            model_name='token',
            name='enabled_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='ZYTxdWbCyotgapCHjNg8DrrGzLpgn5ns', max_length=32, unique=True, verbose_name='Token'),
        ),
    ]
