# Generated by Django 3.2.6 on 2021-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='enabled_count',
            field=models.SmallIntegerField(default=-1, verbose_name='View Limit'),
        ),
    ]
