# Generated by Django 3.2.6 on 2021-08-28 12:19

from django.db import migrations, models
import martor.models
import resources.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('content', martor.models.MartorField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('token', models.ManyToManyField(blank=True, related_name='post_tokens', to='tokens.Token', verbose_name='URL Token')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='files', validators=[resources.validators.file_size_validator])),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_private', models.BooleanField(default=False)),
                ('token', models.ManyToManyField(blank=True, related_name='file_tokens', to='tokens.Token', verbose_name='URL Token')),
            ],
        ),
    ]
