# Generated by Django 3.2.6 on 2021-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
